IrisDashboards/Controllers/EmbassyController.cs
using DotNet.Highcharts;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Options;
using IrisDashboards.Helpers;
using IrisDashboards.Models;
using IrisDashboards_Common;
using IrisDashboards_Proxy;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace IrisDashboards.Controllers
{
    public class EmbassyController : Controller
    {
        #region Variables

        public static DateTime LastUpdate;
        public static List<EmbassyReport> BeforeTodayData;
        public static List<EmbassyReport> TodaysData;
        public static List<EmbassyReport> TotalBeforeToday;
        private Dictionary<string, Dictionary<string, int>> _tempveridata;
        private ChartItem _tempverichart;
        private Dictionary<string, Dictionary<string, int>> _tempuserdata;
        private Dictionary<string, Color> _colourDictionary;
        private ChartItem _tempuserchart;
        private ChartItem _tempPieChart;
        private bool _saveTemp;

        Color Others = ColorTranslator.FromHtml("#467467");
        List<Color> Colours = new List<Color>() {  
            { ColorTranslator.FromHtml("#2f7ed8") },
            { ColorTranslator.FromHtml("#FF7C30") },
            { ColorTranslator.FromHtml("#8bbc21") },
            { ColorTranslator.FromHtml("#910000") },
            { ColorTranslator.FromHtml("#1aadce") },
            { ColorTranslator.FromHtml("#492970") },
            { ColorTranslator.FromHtml("#f28f43") },
            { ColorTranslator.FromHtml("#1E55CC") },
            { ColorTranslator.FromHtml("#c42525") },
            { ColorTranslator.FromHtml("#77a1e5") },
            { ColorTranslator.FromHtml("#99FF99") },
            { ColorTranslator.FromHtml("#666666") }
        };

        #endregion

        #region Actions

        public ActionResult Index()
        {
            ViewBag.Header = "Embassy Passport Verifications";
            DashboardModel model = new DashboardModel();

            // Keep data so we can also get for big chart without having to query for the same thing twice
            _saveTemp = true;

            model.EmbassyVerificationsColumnChart = GetEmbassyPassportVerificationYear(DateTime.Today.AddYears(-1), DateTime.Today, false);
            model.EmbassyVerificationsPieChart = GetEmbassyPassportVerificationPieChart(false);
            model.EmbassyUserRegistrationsColumnChart = GetEmbassyUserRegistration(false);
            model.WeeklyData = GetWeeklyVerificationData();
            model.ViewedPassportsEmbassy = TodaysData;

            // Slider Panel
            model.SliderPanel.Add(new ChartItem() { ChartName = "BigEmbassyVerifications", Chart = GetChartData(_tempveridata, _tempverichart, true), ChartType = "_ChartTemplate" });
            model.SliderPanel.Add(new ChartItem() { ChartName = "BigEmbassyUsers", Chart = GetChartData(_tempuserdata, _tempuserchart, true), ChartType = "_ChartTemplate" });
            model.SliderPanel.Add(new ChartItem() { ChartName = "BigEmbassyVerificationPieChart", Chart = CreatePieChart(_tempPieChart), ChartType = "_ChartTemplate" });

            // Show play buttons
            ViewBag.ShowPlayButtons = 1;

            // Data for the slider
            var names = DateTimeFormatInfo.CurrentInfo?.MonthNames;
            model.MonthList.Add("0", "Full Year");
            for (int i = 0; i < names?.Length; i++)
            {
                if (!string.IsNullOrEmpty(names[i]))
                    model.MonthList.Add((i + 1).ToString(), names[i]);
            }
            model.MonthList.Add("100", "Till Date");

            // years
            for (int i = 2015; i < DateTime.Now.Year + 1; i++)
            {
                model.YearList.Add(i.ToString(), i.ToString());
            }

            // Show refresh
            ViewBag.ShowRefresh = 1;

            return View(model);
        }

        #endregion

        #region Json

        public ActionResult SearchPassportRange(string selectyearval, string selectmonthval)
        {
            var item = new ChartItem();

            if (string.IsNullOrEmpty(selectyearval))
                selectyearval = DateTime.Today.Year.ToString();

            if (string.IsNullOrEmpty(selectmonthval))
                selectmonthval = "0";

            int year = int.Parse(selectyearval);
            int month = int.Parse(selectmonthval);

            if (!string.IsNullOrEmpty(selectmonthval))
            {
                // Get whole year
                if (month == 0)
                {                    
                    item.Chart = GetEmbassyPassportVerificationYear(new DateTime(year, 1, 1), new DateTime(year + 1, 1, 1), true);
                }
                else
                {
                    // Get till today
                    if (month == 100)
                    {
                        item.Chart = GetEmbassyPassportVerificationYear(new DateTime(year, 1, 1), DateTime.Today, true);
                    }
                    else
                    // For a specific month
                        item.Chart = GetEmbassyPassportVerificationMonth(new DateTime(year, month, 1), true);

                }
            }

            return Json(new { success = 1, page = Helper.JsonPartialView(this, "_ChartTemplate", item.Chart) }, JsonRequestBehavior.AllowGet);            
        }

        public ActionResult GetSliderData()
        {
            int newday = 0;
            EmbassyProxy proxy = new EmbassyProxy();

            // If a day has passed or first time running, get piechart data
            if (BeforeTodayData == null || LastUpdate != DateTime.Today)
            {
                BeforeTodayData = proxy.EmbassyChannel.GetBeforeTodaysData();
                LastUpdate = DateTime.Today;
            }

            DashboardModel model = new DashboardModel();

            // Get charts
            if (newday == 1)
            {
                model.EmbassyVerificationsColumnChart = GetEmbassyPassportVerificationYear(DateTime.Today.AddYears(-1), DateTime.Today, false);
                model.EmbassyVerificationsPieChart = GetEmbassyPassportVerificationPieChart(false);
                model.EmbassyUserRegistrationsColumnChart = GetEmbassyUserRegistration(false);
                model.WeeklyData = GetWeeklyVerificationData();
                model.ViewedPassportsEmbassy = TodaysData;

                // Slider Panel
                model.SliderPanel.Add(new ChartItem() { ChartName = "BigEmbassyVerifications", Chart = model.EmbassyVerificationsColumnChart, ChartType = "_ChartTemplate" });
                model.SliderPanel.Add(new ChartItem() { ChartName = "BigEmbassyUsers", Chart = GetChartData(_tempuserdata, _tempuserchart, true), ChartType = "_ChartTemplate" });
                model.SliderPanel.Add(new ChartItem() { ChartName = "BigEmbassyVerificationPieChart", Chart = CreatePieChart(_tempPieChart), ChartType = "_ChartTemplate" });

                return Json(new
                {
                    success = 1,
                    EmbassyVerificationsPieChart = Helper.JsonPartialView(this, "_PieChartTemplate", model.EmbassyVerificationsPieChart),
                    EmbassyVerificationsColumnChart = Helper.JsonPartialView(this, "_ChartTemplate", model.EmbassyVerificationsColumnChart),
                    EmbassyUserRegistrationsColumnChart = Helper.JsonPartialView(this, "_ChartTemplate", model.EmbassyUserRegistrationsColumnChart),
                    page = Helper.JsonPartialView(this, "_SliderPanel", model),
                    ViewedPassportsEmbassy = Helper.JsonPartialView(this, "_MiniPassportReport", model.ViewedPassportsEmbassy),
                    model.WeeklyData.TableData,
                    newday = 1
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                model.ViewedPassportsEmbassy = TodaysData;
                model.WeeklyData = GetWeeklyVerificationData();

                return Json(new
                {
                    success = 1,
                    ViewedPassportsEmbassy = Helper.JsonPartialView(this, "_MiniPassportReport", model.ViewedPassportsEmbassy),
                    model.WeeklyData.TableData,
                    newday = 0
                }, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        #region Charts

        private Highcharts GetEmbassyPassportVerificationPieChart(bool bigChart)
        {
            EmbassyProxy proxy = new EmbassyProxy();

            // If a day has passed or first time running, get piechart data
            if (BeforeTodayData == null || LastUpdate != DateTime.Today)
            {
                BeforeTodayData = proxy.EmbassyChannel.GetBeforeTodaysData();
                LastUpdate = DateTime.Today;
            }

            TodaysData = proxy.EmbassyChannel.GetTodaysData();

            // Add up totals
            int totalbeforetoday = BeforeTodayData.Sum(x => x.Count);
            int totaltoday = TodaysData.Sum(x => x.Count);
            int grandtotal = totalbeforetoday + totaltoday;

            // Get series
            List<object[]> datalist = new List<object[]>();
            double totalperc = 0;
            int counter = 0;
            List<string> colors = new List<string>();

            foreach (EmbassyReport report in BeforeTodayData)
            {
                // Only show for those that are over a given percentage to prevent cluster
                EmbassyReport rep = TodaysData.FirstOrDefault(xAxis => xAxis.DivisionId == report.DivisionId);
                int valplustoday = rep?.Count + report.Count ?? report.Count;
                totalperc += valplustoday;

                if (counter < Colours.Count)
                    colors.Add(ColorTranslator.ToHtml(Colours[counter]));
                else

IrisDashboards/Views/Shared/_ChartTemplate.cshtml
@model DotNet.Highcharts.Highcharts

@(Model)

IrisDashboards/Views/Shared/_DataTemplate.cshtml
@model IrisDashboards.Models.DataTemplateInfo

<div class="pingdomSummary"> 
    <div id="resultPart" class="innerBox light">
        <div id="statusHistoryTable_wrapper" class="dataTables_wrapper" role="grid">
            <div class=""></div>
            <table class="dt withHover dataTable">
                @if (Model.NumberOfCols == 3)
                {
                    <colgroup>
                        <col width="44%">
                        <col width="28%">
                        <col width="28%">
                        <col>
                    </colgroup>
                }
                
                @if (Model.NumberOfCols == 4)
                {
                    <colgroup>
                        <col width="10%">
                        <col width="32%">
                        <col width="31%">
                        <col width="27%">
                        <col>
                    </colgroup>
                }
                
                @if (Model.NumberOfCols == 6)
                {
                    <colgroup>
                        <col width="25%">
                        <col width="15%">
                        <col width="15%">
                        <col width="15%">
                        <col width="15%">
                        <col width="15%">
                        <col>
                    </colgroup>
                }
                
                @if (Model.NumberOfCols == 7)
                {
                    <colgroup>
                        <col width="34%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col>
                    </colgroup>
                }
                
                @if (Model.NumberOfCols == 8)
                {
                    <colgroup>
                        <col width="21%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="14%">
                        <col>
                    </colgroup>
                }

                
                <thead>
                    <tr role="row">
                        @if (!string.IsNullOrEmpty(Model.Header1))
                        {
                            <th class="table-header-dark sorting_disabled" role="columnheader" rowspan="1" colspan="1"><span class="bulb"></span>@Model.Header1</th>
                        }
                        
                        @if (!string.IsNullOrEmpty(Model.Header2))
                        {
                            <th class="table-header-dark sorting_desc" role="columnheader" tabindex="0" rowspan="1" colspan="1">@Model.Header2</th>
                        }
                        
                        @if (!string.IsNullOrEmpty(Model.Header3))
                        {
                            <th class="table-header-dark sorting_disabled sorting_disabled" role="columnheader" rowspan="1" colspan="1">@Model.Header3</th>
                        }
                        
                        @if (!string.IsNullOrEmpty(Model.Header4))
                        {
                            <th class="table-header-dark sorting" role="columnheader" tabindex="0" rowspan="1" colspan="1">@Model.Header4</th>
                        }
                        
                        @if (!string.IsNullOrEmpty(Model.Header5))
                        {
                            <th class="table-header-dark sorting" role="columnheader" tabindex="0" rowspan="1" colspan="1">@Model.Header5</th>
                        }
                        
                        @if (!string.IsNullOrEmpty(Model.Header6))
                        {
                            <th class="table-header-dark sorting" role="columnheader" tabindex="0" rowspan="1" colspan="1">@Model.Header6</th>
                        }
                        
                        @if (!string.IsNullOrEmpty(Model.Header7))
                        {
                            <th class="table-header-dark sorting" role="columnheader" tabindex="0" rowspan="1" colspan="1">@Model.Header7</th>
                        }
                        
                        @if (!string.IsNullOrEmpty(Model.Header8))
                        {
                            <th class="table-header-dark sorting" role="columnheader" tabindex="0" rowspan="1" colspan="1">@Model.Header8</th>
                        }
                        
                        @if (!string.IsNullOrEmpty(Model.Header9))
                        {
                            <th class="table-header-dark sorting" role="columnheader" tabindex="0" rowspan="1" colspan="1">@Model.Header9</th>
                        }
                    </tr>
                </thead>
            </table>
            <table id="DataTemplteTable" class="dt withHover dataTable">
                @if (Model.NumberOfCols == 3)
                {
                    <colgroup>
                        <col width="44%">
                        <col width="28%">
                        <col width="28%">
                        <col>
                    </colgroup>
                }
                
                @if (Model.NumberOfCols == 4)
                {
                    <colgroup>
                        <col width="10%">
                        <col width="32%">
                        <col width="31%">
                        <col width="27%">
                        <col>
                    </colgroup>
                }
                
                @if (Model.NumberOfCols == 6)
                {
                    <colgroup>
                        <col width="25%">
                        <col width="15%">
                        <col width="15%">
                        <col width="15%">
                        <col width="15%">
                        <col width="15%">
                        <col>
                    </colgroup>
                }
                
                @if (Model.NumberOfCols == 7)
                {
                    <colgroup>
                        <col width="34%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col>
                    </colgroup>
                }
                
                @if (Model.NumberOfCols == 8)
                {
                    <colgroup>
                        <col width="21%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="11%">
                        <col width="14%">
                        <col>
                    </colgroup>
                }

                <tbody role="alert" aria-live="polite" aria-relevant="all">
                    @for (int i = 0; i < Model.DataItems.Count; i++)
                    {
                        <tr title="@(!string.IsNullOrEmpty(Model.DataItems[i].ErrorMessage) ? Model.DataItems[i].ErrorMessage : "")" style="@(!string.IsNullOrEmpty(Model.DataItems[i].ErrorMessage) ? "background-color: #FF7F7F" : "");@(Model.DataItems[i].IsBold ? "font-weight: bold" : "");@(Model.DataItems[i].FontSize != 0 ? "font-size: " + Model.DataItems[i].FontSize + "px" : "")" class="@(i % 2 == 0 ? "even" : "odd")">
                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item1))
                            {
                                <td class="">@Model.DataItems[i].Item1</td>
                            }

                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item2))
                            {
                                <td style="@(Model.NumberOfCols == 8 || Model.NumberOfCols == 6 ? "color: #00990F" : "color: #333333"); font-weight: bold; @(string.IsNullOrEmpty(Model.DataItems[i].Item3) ? "border-right:none;" : "")" class=" sorting_1">@Model.DataItems[i].Item2</td>
                            }

                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item3))
                            {
                                <td style="@(Model.NumberOfCols == 8 ? "color: #8D2136" : "color: #333333"); font-weight: bold; @(string.IsNullOrEmpty(Model.DataItems[i].Item4) ? "border-right:none;" : "")" class="">@Model.DataItems[i].Item3</td>
                            }

                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item4))
                            {
                                <td style="@(string.IsNullOrEmpty(Model.DataItems[i].Item5) ? "border-right:none;" : "")">@Model.DataItems[i].Item4</td>
                            }

                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item5))
                            {
                                <td style="@(string.IsNullOrEmpty(Model.DataItems[i].Item6) ? "border-right:none;" : "");">@Model.DataItems[i].Item5</td>
                            }

                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item6))
                            {
                                <td style="@(Model.NumberOfCols == 6 ? "color: #336699;font-weight: bold;" : "")@(Model.NumberOfCols == 7 ? "color: #00990F; font-weight: bold;" : ""); @(string.IsNullOrEmpty(Model.DataItems[i].Item7) ? "border-right:none;" : "")">@Model.DataItems[i].Item6</td>
                            }

                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item7))
                            {
                                <td style="@(Model.NumberOfCols == 7 ? "color: #4283C4; font-weight: bold;" : "color: #333333"); @(string.IsNullOrEmpty(Model.DataItems[i].Item8) ? "border-right:none;" : "")">@Model.DataItems[i].Item7</td>
                            }

                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item8))
                            {
                                <td style="@(string.IsNullOrEmpty(Model.DataItems[i].Item9) ? "border-right:none;" : "")">@Model.DataItems[i].Item8</td>
                            }

                            @if (!string.IsNullOrEmpty(Model.DataItems[i].Item9))
                            {
                                <td style="@(string.IsNullOrEmpty(Model.DataItems[i].Item10) ? "border-right:none;" : "")">@Model.DataItems[i].Item9</td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#socketworksactivitycount').html(@(Model.DataItems.Count));
</script>

IrisDashboards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en" style="overflow: hidden">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="pragma" content="no-cache" />
    <title>Iris Dashboards</title>
    @Styles.Render("~/Content/master")
   
</head>
<body  id="wrapper">
    <header class="header relative">
        <a href="/"><div class="irislogosmall left"></div></a>
        <div class="logosmall left">Iris Dashboards</div>
        <div class="pageheader">@ViewBag.Header</div>
        @if (ViewBag.ShowRefresh == 1)
        {
            <div class="startSlide hoverfade right"></div>
        }
        <div class="clear"></div>
    </header>

    <div id="content2" style="width: auto;">
        @RenderSection("featured", required: false)
        <section class="main-content clear-fix" style="height: 100%; position: relative">
            @RenderBody()
        </section>
    </div>

    <footer>
        <div class="footernote">©@(DateTime.Now.Year) - Iris Smart Technologies Ltd</div>
    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>

IrisDashboards/Views/Shared/_PieChartTemplate.cshtml
@model DotNet.Highcharts.Highcharts
@{
    ViewBag.Title = "Pie With Gradient Fill";
}

<script type="text/javascript">
    $(function () {
        // Radialize the colors
        Highcharts.getOptions().colors = [@Html.Raw(ViewBag.Colors)];
        Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, function (color) {
            return {
                radialGradient: { cx: 0.5, cy: 0.3, r: 0.7 },
                stops: [
		            [0, color],
		            [1, Highcharts.Color(color).brighten(-0.3).get('rgb')] // darken
                ]
            };
        });
    });
</script>


@(Model)

IrisDashboards/Views/Shared/_SliderPanel.cshtml
@model IrisDashboards.Models.DashboardModel

<script src="/Scripts/General/sliderpanel.js" type="text/javascript"> </script>

<ul id="slider">
    @foreach (IrisDashboards.Models.ChartItem chart in Model.SliderPanel)
    {
        <li>
            @if (chart.ChartName == "BigEmbassyVerifications")
            {
                <div id="PassportVerificationDiv">
                    <div class="modal"></div>
                    <div style="position: absolute; width: 100%; background-color: White; z-index: 1">
                        <div id="PassportVerificationAll" class="graph">@Html.Partial("_ChartTemplate", chart.Chart)</div>
                    </div>   
                    <div class="graphinfoparent">
                        <div class="hideme button">Hide</div>
                        <div class="shadow graphinfodiv">
                            <form method="post" action="@Url.Action("SearchPassportRange", "Embassy")" data-partial="true" data-target="PassportVerificationAll">
                                <div style="margin-bottom: 15px">
                                    <div class="infobox">Year</div>
                                    @Html.Hidden("selectyearval")
                                    <select id="selectyear" class="selectbox">
                                        <option></option>
                                        @foreach (KeyValuePair<string, string> year in Model.YearList)
                                        {
                                            <option value="@year.Key">@year.Value</option>
                                        }
                                    </select>
                                </div>
                                <div style="margin-bottom: 5px; position:relative">
                                    <div class="infobox">Month</div>
                                    @Html.Hidden("selectmonthval")
                                    <select id="selectmonth" class="selectbox">
                                        <option></option>
                                        @foreach (KeyValuePair<string, string> month in Model.MonthList)
                                        {
                                            <option value="@month.Key">@month.Value</option>
                                        }
                                    </select>
                                </div>

                                <div class="spacetop">
                                    <input class="button updatebtn right" type="submit" value="Update" />
                                    <div class="loadingdiv right">
                                        <div class="smallmodal"></div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </form>
                        </div>
                    </div>                 
                </div>
            }
            else if (chart.ChartName == "BigPassportReportPieChart")
            {
                <div id="@chart.ChartName" class="graph">@Html.Partial(chart.ChartType, chart.Chart, new ViewDataDictionary { { "Colors", ViewBag.BranchColors } } )</div>
            }
            else
            {
                <div id="@chart.ChartName" class="graph">@Html.Partial(chart.ChartType, chart.Chart)</div>
            }
        </li>
    }
</ul>

IrisDashboards/Views/Shared/_ViewPassport.cshtml
@model IrisDashboards_Common.Report

<div class="closebtn closeme">X</div>
<div class="reportFace left">
    <img id="faceimg" width="195" height="260" alt="" src="data:image/png;base64,@System.Convert.ToBase64String(Model.FaceImage)" />
</div>
<div style="width: 130px" class="left">
    <div class="infoline">
        <div class="labelleft">Firstname:</div>
        <div class="labelright"> @IrisDashboards_Common.Helper.Helper.ToFirstLetterUpper(Model.FirstName.ToLower())</div>
    </div>
    <div class="infoline">
        <div class="labelleft">Surname:</div>
        <div class="labelright"> @IrisDashboards_Common.Helper.Helper.ToFirstLetterUpper(Model.Surname.ToLower())</div>
    </div>
    <div class="infoline">
        <div class="labelleft">Gender:</div>
        <div class="labelright"> @(Model.Sex == "F" ? "Female" : "Male")</div>
    </div>
    <div class="infoline">
        <div class="labelleft">StageCode:</div>
        <div class="labelright"> @Model.Stage_Code</div>
    </div>
    <div class="infoline">
        <div class="labelleft">Date Of Birth:</div>
        <div class="labelright"> @(Model.DOB.ToString("dd/MM/yyyy"))</div>
    </div>
</div>
<div class="clear"></div>